/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: "https://aristagroup.es",
  generateRobotsTxt: true,
  changefreq: "weekly",
  priority: 0.8,
  sitemapSize: 5000,
  exclude: ["/privacidad", "/cookies", "/api/*", "/admin", "/admin/*"],
  robotsTxtOptions: {
    policies: [
      { userAgent: "*", allow: "/" },
      { userAgent: "*", disallow: ["/api/", "/admin/"] },
    ],
  },
  additionalPaths: async () => [
    { loc: "/",                          priority: 1.0, changefreq: "daily"  },
    { loc: "/movil",                     priority: 0.9, changefreq: "weekly" },
    { loc: "/energia",                   priority: 0.9, changefreq: "weekly" },
    { loc: "/fibra-energia",             priority: 0.9, changefreq: "weekly" },
    { loc: "/tarifas",                   priority: 0.9, changefreq: "weekly" },
    { loc: "/tarifas/fibra",             priority: 0.9, changefreq: "weekly" },
    { loc: "/cobertura",                 priority: 0.8, changefreq: "weekly" },
    { loc: "/empresas",                  priority: 0.8, changefreq: "weekly" },
    { loc: "/empresas/autonomos",        priority: 0.7, changefreq: "weekly" },
    { loc: "/empresas/pymes",            priority: 0.7, changefreq: "weekly" },
    { loc: "/empresas/corporaciones",    priority: 0.7, changefreq: "weekly" },
    { loc: "/cambia-de-compania",        priority: 0.8, changefreq: "weekly" },
    { loc: "/fibra-barata-alicante",     priority: 0.9, changefreq: "weekly" },
    { loc: "/movil-barato-alicante",     priority: 0.9, changefreq: "weekly" },
    { loc: "/fibra-torrevieja",          priority: 0.8, changefreq: "weekly" },
    { loc: "/fibra-ibiza",               priority: 0.8, changefreq: "weekly" },
    { loc: "/fibra-orange-alicante",     priority: 0.8, changefreq: "weekly" },
    { loc: "/operadora-local-alicante",  priority: 0.8, changefreq: "weekly" },
    { loc: "/entender-factura",          priority: 0.7, changefreq: "monthly" },
    { loc: "/hogueras",                  priority: 1.0, changefreq: "daily"  },
    { loc: "/fibra-y-movil",                       priority: 0.8, changefreq: "weekly" },
    { loc: "/mejor-compania-fibra-movil-luz",      priority: 1.0, changefreq: "weekly" },
    { loc: "/fibraempresabarata",                  priority: 0.9, changefreq: "weekly" },
  ],
};
